# Copyright (C) 2024 Cadiou Didier <didier.cadiou@unicaen.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


- name: script de contrôle
  ansible.builtin.template:
    src: check_fix_course_sequence.sh.j2
    dest: /opt/check_fix_course_sequence.sh
    owner: "{{dataroot_dir_owner}}"
    group: "{{dataroot_dir_group}}"
    mode: "{{dataroot_dir_mode}}"

- name: cron de controle des "course sequence"
  ansible.builtin.cron:
    name: 'Cron controle course_sequence (géré par ANSIBLE, NE PAS TOUCHER ICI) :' # ce nom identifie l'entrée dans le crontab.
      # S'il est modifié, une nouvelle entrée est créé
    user: ...
    disabled: true # Vu les risques d'une exécution dans un contexte non préparé...
    job: 'bash /opt/check_fix_course_sequence.sh'
    minute: ...

- name: cron de correction des "course sequence"
  ansible.builtin.cron:
    name: 'Cron correction course_sequence (géré par ANSIBLE, NE PAS TOUCHER ICI) :' # ce nom identifie l'entrée dans le crontab.
      # S'il est modifié, une nouvelle entrée est créé
    user: ...
    disabled: false # Vu les risques d'une exécution dans un contexte non préparé...
    job: 'php {{moodle_dir}}/admin/cli/fix_course_sequence.php -c=* --fix 1> /dev/null 2>> {{log_output}}'
    hour: ...
    minute: ...
  vars:
    log_output: ...

- name: configuration conservation des log de fix_course_sequence
  ansible.builtin.copy:
    src: ...
    dest: ...
