# Copyright (C) 2024 Cadiou Didier <didier.cadiou@unicaen.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Voir https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#how-to-enable-the-debsuryorg-repository
# Attention : apt_key est obsolète
- name: ajout depot sury.org
  when:
    - container_docker is defined # sur les serveurs de la DSI les paquets php sont dans le depot unicaen
  block:

    - name: ajout depot sury.org sous debian
      when:
        - ansible_facts['distribution'] == 'Debian'
      block:

        - name: Importer la clé APT du dépôt Sury
          ansible.builtin.get_url:
            url: https://packages.sury.org/php/apt.gpg
            dest: /usr/share/keyrings/deb.sury.org-php.gpg

        - name: Déclarer le dépôt Sury pour Debian
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
            state: present
            filename: php

    - name: ajout depot sury.org sous Ubuntu
      when:
        - ansible_facts['distribution'] == 'Ubuntu'
      block:

        - name: Ajout du PPA du dépôt Sury sur Ubuntu
          ansible.builtin.apt_repository:
            repo: ppa:ondrej/php

- name: Installer les paquetages necessaires
  ansible.builtin.apt:
    name:
      - ...
      - php{{php_version}}
      - ...
    state: present
    install_recommends: false

- name: Installer les paquetages d'extension de php
  ansible.builtin.apt:
    name:
      - php{{php_version}}-common
      - ...
    state: present
    install_recommends: false

- name: 'Fichier de configuration module {{application}}'
  ansible.builtin.template:
    src: '{{application}}.ini.j2'
    dest: /...

- name: 'Activation du module {{application}}'
  ansible.builtin.command:
    cmd: "phpenmod -v {{php_version}} {{application}}"
  notify:
    - service_php_reload
    - check_phpinfo_ok
